### ISSUE TITLE
Retry introduced significant delays in VCN operations

### ISSUE THREAD

**Issue by qrdl** [vchain-us/ledger-compliance-go#60]
After addition of retries VCN operations became much slower.

Commit before retry changes:

```
$ go get github.com/vchain-us/ledger-compliance-go@dadda9f4b5514c85f2fed4f78eaa332b58ac89a1
...
$ make
...
$ time ./vcn a vcn

Warning: 008990c65fa433ed7b0696990da7306a3553a538653c34a4761d1e8b5e65794d was not notarized

real	0m0.186s
user	0m0.159s
sys	0m0.023s
```
Last commit with retry changes:
```
$ go get github.com/vchain-us/ledger-compliance-go@309f3c068f0050c37556bf2e423b40752c8e0063
...
$ make
...
$ time ./vcn a vcn

Warning: 1fc99bf465f0c8cf560b9f6a7cc4a44d0a721d09aaaf436e6175c8d4c8c2556c was not notarized

real	0m5.009s
user	0m0.144s
sys	0m0.063s
```
In `dataservice` I see that `VCNGetArtifacts` is called 3 times instead of 1 (as it was before the change). Everything (`immudb`, `dataservice`, `vcn`) is running locally so there is no reasons for retries. This problem occurs every single I run `vcn a` or `vcn n`.

**Comment by arturmelanchyk** [comment]
it happens because here we do retries when server responds with an error.
https://github.com/codenotary/vcn-enterprise/blob/5169af3bd38b9fab9741e03544bcc0c69d29f580/pkg/api/lc_artifact.go#L317-L329

somehow here "key not found" error is not handled correctly and will lead to 500 status code https://github.com/vchain-us/codenotary-cloud/blob/5a53a04918c85dfcd469a3c2ec05d4ba0f6983a3/server/internal/grpc/error_interceptor.go#L43-L50

whereas in sentinel checks it will always appear as 400 https://github.com/vchain-us/codenotary-cloud/blob/5a53a04918c85dfcd469a3c2ec05d4ba0f6983a3/server/internal/sentinel/sentinel.go#L310-L317

I suggest to extend error checks with "key not found" in errors_interceptor

Also, immudb always returns errors with code 2 "Unknown" (which retrier configured to retry). This has to be fixed either on immudb side or we need to override all errors that we receive from immudb. Or we can configure retrier to not retry such codes which can potentially make it useless

**Comment by arturmelanchyk** [comment]
https://github.com/codenotary/immudb/issues/1255

**Comment by tomekkolo** [comment]
@qrdl , let's disable retry and by default have 0 for now in vcn. We discussed and this will need to be handled in immudb most probably (cc @byo , @ldej , @raducrisan1 , @joe-mann )

https://github.com/codenotary/vcn-enterprise/blob/5169af3bd38b9fab9741e03544bcc0c69d29f580/pkg/cmd/cmd.go#L96

**Comment by qrdl** [comment]
> @qrdl , let's disable retry and by default have 0 for now in vcn. We discussed and this will need to be handled in immudb most probably (cc @byo , @ldej , @raducrisan1 , @joe-mann )

The branch I'm working on was branched off `develop` before retries were introduced, so there is no `retry-attempts` param at all, but it still retries 3 times because it is a default set in `ledger-compliance-go`: https://github.com/vchain-us/ledger-compliance-go/blob/master/grpcclient/lc_client.go#L164
Until I merge my changes I cannot change this parameter.

**Comment by tomekkolo** [comment]
> > @qrdl , let's disable retry and by default have 0 for now in vcn. We discussed and this will need to be handled in immudb most probably (cc @byo , @ldej , @raducrisan1 , @joe-mann )
> 
> The branch I'm working on was branched off `develop` before retries were introduced, so there is no `retry-attempts` param at all, but it still retries 3 times because it is a default set in `ledger-compliance-go`: https://github.com/vchain-us/ledger-compliance-go/blob/master/grpcclient/lc_client.go#L164 Until I merge my changes I cannot change this parameter.

Ah ok, so we need to change default in ledger complaiance.

**Comment by tomekkolo** [comment]
@raducrisan1 after merging https://github.com/vchain-us/ledger-compliance-go/pull/61, please do not forget to update dependency to ledger compliance go in vcn-enterprise develop branch.

**Comment by raducrisan1** [comment]
A pull request has been created on vcn-enterprise, checks passed, approved and merged to develop. Link to PR: https://github.com/codenotary/vcn-enterprise/pull/452

**Comment by qrdl** [comment]
Issue has been fixed
